version: 1.0

server:
  host: 0.0.0.0
  port: 8080
databases:
  postgres:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    db: liquide
    sslmode: disable
    connect_timeout: 10
  redis:
    host: 127.0.0.1
    port: 6379
auth:
  key: f66b73f12706b9d36e9940525c21654b89d2f7f5921fd9e96bbf0e0e45168909